import assert from "node:assert/strict";
import { test } from "node:test";

import { AgentRuntime, ContextBuilder, FileSessionStateStore, JsonlEventStore, LocalMemorySurface, LocalMemoryTuiController, PermissionManager, Replay, ToolExecutor, executeAgentCli, executeMemoryCli, executeMemoryTuiCommand, parseAgentCliArgv, parseMemoryCliArgv, parseMemoryTuiCommand, runAgentRepl, runMemoryCli } from "../src/index.ts";
import * as agentCliModule from "../src/agent-cli.ts";
import * as runtimeModule from "../src/runtime.ts";
import * as contextModule from "../src/context.ts";
import * as eventModule from "../src/events.ts";
import * as memoryModule from "../src/memory.ts";
import * as permissionModule from "../src/permissions.ts";
import * as replayModule from "../src/replay.ts";
import * as toolModule from "../src/tools.ts";
import * as typesModule from "../src/types.ts";

test("split modules remain importable and barrel exports preserve the public surface", () => {
  assert.equal(typeof AgentRuntime, "function");
  assert.equal(typeof ContextBuilder, "function");
  assert.equal(typeof FileSessionStateStore, "function");
  assert.equal(typeof JsonlEventStore, "function");
  assert.equal(typeof LocalMemorySurface, "function");
  assert.equal(typeof LocalMemoryTuiController, "function");
  assert.equal(typeof PermissionManager, "function");
  assert.equal(typeof Replay, "function");
  assert.equal(typeof ToolExecutor, "function");
  assert.equal(typeof parseAgentCliArgv, "function");
  assert.equal(typeof executeAgentCli, "function");
  assert.equal(typeof runAgentRepl, "function");
  assert.equal(typeof runMemoryCli, "function");
  assert.equal(typeof parseMemoryCliArgv, "function");
  assert.equal(typeof executeMemoryCli, "function");
  assert.equal(typeof parseMemoryTuiCommand, "function");
  assert.equal(typeof executeMemoryTuiCommand, "function");

  assert.equal(agentCliModule.parseAgentCliArgv, parseAgentCliArgv);
  assert.equal(agentCliModule.executeAgentCli, executeAgentCli);
  assert.equal(agentCliModule.runAgentRepl, runAgentRepl);
  assert.equal(runtimeModule.AgentRuntime, AgentRuntime);
  assert.equal(contextModule.ContextBuilder, ContextBuilder);
  assert.equal(eventModule.JsonlEventStore, JsonlEventStore);
  assert.equal(memoryModule.LocalMemorySurface, LocalMemorySurface);
  assert.equal(memoryModule.LocalMemoryTuiController, LocalMemoryTuiController);
  assert.equal(memoryModule.runMemoryCli, runMemoryCli);
  assert.equal(memoryModule.parseMemoryCliArgv, parseMemoryCliArgv);
  assert.equal(memoryModule.executeMemoryCli, executeMemoryCli);
  assert.equal(memoryModule.parseMemoryTuiCommand, parseMemoryTuiCommand);
  assert.equal(memoryModule.executeMemoryTuiCommand, executeMemoryTuiCommand);
  assert.equal(permissionModule.PermissionManager, PermissionManager);
  assert.equal(replayModule.Replay, Replay);
  assert.equal(toolModule.ToolExecutor, ToolExecutor);
  assert.equal(typeof typesModule, "object");
});
